filter:
    excluded_paths:
        - 'extras/libraries/*'
        - 'libraries/phpopenid/Auth/*'
        - 'extras/plugins/*'
        - 'libraries/geshi/*'
        - 'libraries/smarty/internals/*'
        - 'htdocs/editors/FCKeditor/*'
        - 'htdocs/install/modules/protector/trust_path/modules/protector/filters_byconfig/*'
        - 'htdocs/install/modules/protector/root/*'
        - 'libraries/image-editor/*'
        - 'libraries/smarty/icms_plugins/*'
        - 'plugins/sourceeditors/*'
        - 'plugins/csstidy/*'
        - 'upgrade/upd-icms-1.0-to-1.1/*'
        - 'libraries/phpopenid/admin/*'
        - 'htdocs/install/modules/protector/trust_path/modules/protector/class/*'
        - 'plugins/rating/*'
        - 'plugins/autotasks/*'
        - 'htdocs/editors/dhtmltextarea/*'
        - 'htdocs/install/modules/protector/trust_path/modules/protector/language/*'
        - 'libraries/wideimage/lib/vendor/de77/*'
        - 'extras/ssl/*'
        - 'upgrade/language/*'
        - upgrade/index.php
        - upgrade/login.php
        - mainfile.php
        - 'plugins/waiting/*'
        - upgrade/upgrade_tpl.php
        - 'libraries/xml/rss/*'
        - 'libraries/recaptcha/*'
        - 'upgrade/cnt-2.2.x-to-2.0.x/*'
        - 'upgrade/cnt-2.3.x-to-2.0.x/*'
        - 'upgrade/upd-2.0.13-to-2.0.14/*'
        - 'upgrade/upd-2.0.15-to-2.0.16/*'
        - 'upgrade/upd-2.0.16-to-2.0.17/*'
        - 'upgrade/upd-2.0.17-to-2.0.18/*'
        - install/page_start.php
        - 'libraries/icms/ipf/seo/*'
        - 'libraries/simplepie/idn/*'
        - 'htdocs/editors/tinymce/language/*'
        - htdocs/install/page_no_php5.php
        - htdocs/install/page_siteinit.php
        - language/english/core.php
        - language/english/mail.php
        - libraries/tcpdf/tcpdf.php
        - htdocs/install/page_safe_mode.php
        - libraries/tcpdf/pdf417.php
        - libraries/tcpdf/qrcode.php
        - htdocs/editors/tinymce/tinymce.php
        - libraries/xml/saxparser.php
        - libraries/tcpdf/barcodes.php
        - 'upgrade/upd-2.0.18-to-impresscms-1.0/*'
        - libraries/icms/db/IUtility.php
        - libraries/tcpdf/2dbarcodes.php
        - libraries/tcpdf/datamatrix.php
        - libraries/tcpdf/htmlcolors.php
        - libraries/tcpdf/spotcolors.php
        - libraries/xml/rpc/xoopsapi.php
        - libraries/tcpdf/fonts/times.php
        - libraries/xml/rpc/xmlrpcapi.php
    dependency_paths:
        - 'extras/libraries/*'
        - 'libraries/phpopenid/Auth/*'
        - 'extras/plugins/*'
        - 'libraries/geshi/*'
        - 'libraries/smarty/internals/*'
        - 'htdocs/editors/FCKeditor/*'
        - 'htdocs/install/modules/protector/trust_path/modules/protector/filters_byconfig/*'
        - 'htdocs/install/modules/protector/root/*'
        - 'libraries/image-editor/*'
        - 'libraries/smarty/icms_plugins/*'
        - 'plugins/sourceeditors/*'
        - 'plugins/csstidy/*'
        - 'upgrade/upd-icms-1.0-to-1.1/*'
        - 'libraries/phpopenid/admin/*'
        - 'htdocs/install/modules/protector/trust_path/modules/protector/class/*'
        - 'plugins/rating/*'
        - 'plugins/autotasks/*'
        - 'htdocs/editors/dhtmltextarea/*'
        - 'htdocs/install/modules/protector/trust_path/modules/protector/language/*'
        - 'libraries/icms/sys/*'
        - 'libraries/icms/db/mysql/*'
        - 'libraries/wideimage/lib/vendor/de77/*'
        - 'extras/ssl/*'
        - 'upgrade/language/*'
        - upgrade/index.php
        - upgrade/login.php
        - htdocs/mainfile.php
        - 'plugins/waiting/*'
        - upgrade/upgrade_tpl.php
        - 'libraries/xml/rss/*'
        - htdocs/include/jalali.php
        - libraries/icms.php
        - upgrade/check_version.php
        - 'libraries/recaptcha/*'
        - 'upgrade/cnt-2.2.x-to-2.0.x/*'
        - 'upgrade/cnt-2.3.x-to-2.0.x/*'
        - 'upgrade/upd-2.0.13-to-2.0.14/*'
        - 'upgrade/upd-2.0.15-to-2.0.16/*'
        - 'upgrade/upd-2.0.16-to-2.0.17/*'
        - 'upgrade/upd-2.0.17-to-2.0.18/*'
        - htdocs/install/page_start.php
        - 'libraries/icms/ipf/seo/*'
        - htdocs/include/rating.rate.php
        - 'libraries/simplepie/idn/*'
        - 'htdocs/editors/tinymce/language/*'
        - htdocs/install/page_no_php5.php
        - libraries/icms/Event.php
        - htdocs/install/page_siteinit.php
        - language/english/core.php
        - language/english/mail.php
        - libraries/tcpdf/tcpdf.php
        - htdocs/install/page_safe_mode.php
        - language/english/error.php
        - language/english/theme.php
        - 'libraries/paginationstyles/*'
        - libraries/tcpdf/pdf417.php
        - libraries/tcpdf/qrcode.php
        - htdocs/editors/tinymce/tinymce.php
        - 'libraries/icms/ipf/registry/*'
        - libraries/icms/ipf/Tree.php
        - libraries/xml/saxparser.php
        - language/english/captcha.php
        - libraries/tcpdf/barcodes.php
        - language/english/uploader.php
        - 'htdocs/modules/system/admin/mimetype/*'
        - htdocs/modules/system/admin/tags.php
        - htdocs/modules/system/class/Tags.php
        - 'upgrade/upd-2.0.18-to-impresscms-1.0/*'
        - libraries/icms/db/IUtility.php
        - libraries/tcpdf/2dbarcodes.php
        - libraries/tcpdf/datamatrix.php
        - libraries/tcpdf/htmlcolors.php
        - libraries/tcpdf/spotcolors.php
        - libraries/xml/rpc/xoopsapi.php
        - plugins/preloads/bootstrap.php
        - plugins/preloads/protector.php
        - language/english/privpolicy.php
        - 'libraries/icms/auth/method/ldap/*'
        - libraries/tcpdf/fonts/times.php
        - libraries/xml/rpc/xmlrpcapi.php
checks:
    php:
        duplication: true
        unused_methods: false
        unused_parameters: false
        argument_type_checks: false
        verify_property_names: false
        method_calls_on_non_object: false
        fix_doc_comments: false
        instanceof_class_exists: false
        catch_class_exists: false
        assignment_of_null_return: false
        use_statement_alias_conflict: false
tools:
    php_sim:
        enabled: true
        min_mass: 50             # Defaults to 16
coding_style:
    php:
        indentation:
            general:
                use_tabs: true
                size: 4
            switch:
                indent_case: true
        spaces:
            around_operators:
                concatenation: true
            ternary_operator:
                before_condition: false
                after_condition: false
                before_alternative: false
                after_alternative: false
        braces:
            classes_functions:
                class: end-of-line
                function: end-of-line
                closure: end-of-line
            if:
                opening: end-of-line
            for:
                opening: end-of-line
            while:
                opening: end-of-line
            do_while:
                opening: end-of-line
            switch:
                opening: end-of-line
            try:
                opening: end-of-line
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: lower