filter:
    excluded_paths:
        - htdocs/libraries/smarty/Config_File.class.php
        - htdocs/libraries/smarty/Smarty_Compiler.class.php 
        - htdocs/libraries/smarty/Smarty.class.php
        - 'htdocs/libraries/smarty/plugins/*'
        - 'htdocs/libraries/phpopenid/Auth/*'
        - 'extras/plugins/*'
        - 'htdocs/libraries/geshi/*'
        - 'htdocs/libraries/smarty/internals/*'
        - 'htdocs/editors/FCKeditor/*'
        - 'htdocs/libraries/image-editor/*'
        - 'htdocs/libraries/smarty/icms_plugins/*'
        - 'htdocs/plugins/sourceeditors/*'
        - 'htdocs/plugins/csstidy/*'
        - 'htdocs/libraries/phpopenid/admin/*'
        - 'htdocs/editors/dhtmltextarea/*'
        - 'htdocs/libraries/wideimage/lib/vendor/de77/*'
        - htdocs/mainfile.php
        - 'htdocs/libraries/xml/rss/*'
        - 'htdocs/libraries/recaptcha/*'
        - 'htdocs/editors/tinymce/language/*'
        - htdocs/editors/tinymce/tinymce.php
        - htdocs/libraries/xml/saxparser.php
        - htdocs/libraries/xml/rpc/xoopsapi.php
        - htdocs/libraries/xml/rpc/xmlrpcapi.php
    dependency_paths:
        - htdocs/libraries/smarty/Config_File.class.php
        - htdocs/libraries/smarty/Smarty_Compiler.class.php 
        - htdocs/libraries/smarty/Smarty.class.php
        - 'htdocs/libraries/smarty/plugins/*'
        - 'extras/libraries/*'
        - 'htdocs/libraries/phpopenid/Auth/*'
        - 'extras/plugins/*'
        - 'htdocs/libraries/geshi/*'
        - 'htdocs/libraries/smarty/internals/*'
        - 'htdocs/editors/FCKeditor/*'
        - 'htdocs/libraries/image-editor/*'
        - 'htdocs/libraries/smarty/icms_plugins/*'
        - 'htdocs/plugins/csstidy/*'
        - 'htdocs/libraries/phpopenid/admin/*'
        - 'htdocs/plugins/rating/*'
        - 'htdocs/plugins/autotasks/*'
        - 'htdocs/editors/dhtmltextarea/*'
        - 'htdocs/libraries/icms/sys/*'
        - 'htdocs/libraries/icms/db/mysql/*'
        - 'htdocs/libraries/wideimage/*'
        - htdocs/mainfile.php
        - 'htdocs/plugins/waiting/*'
        - 'htdocs/libraries/xml/rss/*'
        - htdocs/include/jalali.php
        - htdocs/libraries/icms.php
        - 'htdocs/libraries/recaptcha/*'
        - htdocs/install/page_start.php
        - 'htdocs/libraries/icms/ipf/seo/*'
        - htdocs/include/rating.rate.php
        - 'htdocs/editors/tinymce/language/*'
        - htdocs/install/page_no_php5.php
        - htdocs/libraries/icms/Event.php
        - htdocs/install/page_siteinit.php
        - htdocs/install/page_safe_mode.php
        - 'htdocs/libraries/paginationstyles/*'
        - htdocs/editors/tinymce/tinymce.php
        - 'htdocs/libraries/icms/ipf/registry/*'
        - htdocs/libraries/icms/ipf/Tree.php
        - htdocs/libraries/xml/saxparser.php
        - 'htdocs/language/*'
        - 'htdocs/modules/system/admin/mimetype/*'
        - htdocs/modules/system/admin/tags.php
        - htdocs/modules/system/class/Tags.php
        - htdocs/libraries/icms/db/IUtility.php
        - htdocs/libraries/xml/rpc/xoopsapi.php
        - htdocs/plugins/preloads/bootstrap.php
        - 'htdocs/libraries/icms/auth/method/ldap/*'
        - htdocs/libraries/xml/rpc/xmlrpcapi.php
checks:
    php:
        duplication: true
        unused_methods: false
        unused_parameters: true
        argument_type_checks: false
        verify_property_names: false
        method_calls_on_non_object: true
        fix_doc_comments: false
        instanceof_class_exists: false
        catch_class_exists: false
        assignment_of_null_return: false
        use_statement_alias_conflict: false
tools:
    php_sim:
        enabled: true
        min_mass: 50             # Defaults to 16
coding_style:
    php:
        indentation:
            general:
                use_tabs: true
                size: 4
            switch:
                indent_case: true
        spaces:
            around_operators:
                concatenation: true
            ternary_operator:
                before_condition: false
                after_condition: false
                before_alternative: false
                after_alternative: false
        braces:
            classes_functions:
                class: end-of-line
                function: end-of-line
                closure: end-of-line
            if:
                opening: end-of-line
            for:
                opening: end-of-line
            while:
                opening: end-of-line
            do_while:
                opening: end-of-line
            switch:
                opening: end-of-line
            try:
                opening: end-of-line
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: lower
build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
